name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: services/checkout@v3

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: services/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install

      - name: Build production project
        run: npm run build:prod
        if : always()

      - name: Linting TypeScript
        run: npm run lint:ts
        if : always()

      - name: Linting CSS
        run: npm run lint:scss
        if : always()

      - name: Unit testing
        run: npm run test:unit
        if : always()

      - name: build storybook
        run: npm run storybook:build
        if : always()
      - name: screenshot testing
        run: npm run test:ui:ci
